### ISSUE TITLE
NotFoundError: data/mscoco_label_map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by DennisFaucher** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#6]
Thank you for the notebook. I am running in Google Colab. In the Loadin Label Map section, this code block leads to the above error. Is there a step missing that creates the "data" directory? TIA.

````Python
# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = 'data/mscoco_label_map.pbtxt'
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)
````

**Comment by TannerGilbert** [comment]
I just rewrote the file so it works correctly with Google Colab. I also renamed it to [live_object_detection.ipynb](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0/blob/master/live_object_detection.ipynb), because it can be used for all sorts of video streams. Furthermore, I also added two other examples to the repository.

I hope this solves your issue. I will close this issue for now. If you have any further questions feel free to ask.

**Comment by DennisFaucher** [comment]
Thank you. Final step is broken though.

for image_path in TEST_IMAGE_PATHS:
    run_inference(masking_model, cap)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-20-357700788fda> in <module>()
----> 1 for image_path in TEST_IMAGE_PATHS:
      2     run_inference(masking_model, cap)

NameError: name 'TEST_IMAGE_PATHS' is not defined

**Comment by TannerGilbert** [comment]
Removed the code at the end of the notebook, since it wasn't meant to be there in the first place
