### ISSUE TITLE
Outdated tutorial in offical documentation

### ISSUE THREAD

**Issue by naga-k** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#9]
Hey, I'm trying to learn object detection on Tensorflow

[Tensotflow object detection](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_saved_model.html)

And on line, `category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,
                                                                    use_display_name=True)`

I get the error:

AttributeError: module 'tensorflow' has no attribute 'gfile'

![image](https://user-images.githubusercontent.com/29381705/117725176-65a62c80-b202-11eb-8236-bfe670fbed3a.png)

According to what I understand the error is because the function has been moved after Tensorflow 1.14.0 but the API has not been updated.

**Comment by TannerGilbert** [comment]
Are you sure you installed the newest version of the Tensorflow 2 OD API, because for the newest version they [already changed the code](https://github.com/tensorflow/models/blob/09bf9d0e1b87ace54445478a6dbdd4e924416fac/research/object_detection/utils/label_map_util.py#L167) to use `tf.io.gfile.GFile` instead of `tf.gfile.GFile`.
